### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by b4sik** [Topinambur223606/PixelPlanetTools#12]
maybe somehow auto-complete captcha using https://github.com/dessant/buster   ??

**Comment by Topinambur223606** [comment]
Autoresolving captcha may result in massive proxy usage as it was just before captcha appeared.
Also, it means adding browser to the bot. At the moment bot is relatively small, while browser is almost hundred times bigger and has a lot of files that cannot be joined into one.
Therefore, I would not implement such functionality.
