### ISSUE TITLE
Bot problem

### ISSUE THREAD

**Issue by msenya25** [Topinambur223606/PixelPlanetTools#15]
He asks to pass the captcha, even when it is passed.
Log file: [a.txt](https://github.com/Topinambur223606/PixelPlanetTools/files/4568297/a.txt)

**Comment by Lalna-Rocks** [comment]
Looks like the creator nuked the bot because caught on to his silliness.

**Comment by Topinambur223606** [comment]
It's because something is updated on server side
Investigating at the moment

**Comment by BTARD1488** [comment]
working version: https://github.com/BTARD1488/PixelPlanetBotFixed

**Comment by BTARD1488** [comment]
> It's because something is updated on server side
> Investigating at the moment

Just change the httpwebrequest user agent to 
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"

**Comment by Topinambur223606** [comment]
Thank you very much for cooperation, I'll update it soon.

**Comment by BTARD1488** [comment]
![datasclass](https://user-images.githubusercontent.com/64713248/80895151-af833b00-8caf-11ea-919c-3fe206fb29db.PNG)
i think i made some changes to this as well

**Comment by Myrek12** [comment]
> Thank you very much for cooperation, I'll update it soon.

then hurry up

**Comment by b44rt** [comment]
> Thank you very much for cooperation, I'll update it soon.

Fork or wait, will it be today ?

**Comment by Topinambur223606** [comment]
OK, same problem appeared again

**Comment by Myrek12** [comment]
> OK, same problem appeared again

fast go go! 🥇

**Comment by 0xJoey** [comment]
Found the problem. It has to do with the lack of an `Accept-Language` header. Simply adding the following line to HttpWrapper.cs:SendRequest() fixed it for me

`request.Headers["Accept-Language"] = "en-US,en;q=0.5";`

**Comment by msenya25** [comment]
![image](https://user-images.githubusercontent.com/29750228/80932840-12c1ba00-8de3-11ea-95af-62f628dc0a2d.png)
Again that's problem.

**Comment by Topinambur223606** [comment]
Well it seems that the issue is solved.
@msenya25, please close if it is.
