### ISSUE TITLE
problem with connection. 

### ISSUE THREAD

**Issue by msenya25** [Topinambur223606/PixelPlanetTools#20]
![image](https://user-images.githubusercontent.com/29750228/81899293-4e773380-95dc-11ea-83d0-0296e1dfe20e.png)

**Comment by Topinambur223606** [comment]
API has changed, working on it right now. Update will be rolled out soon.

**Comment by WizTheLichLover** [comment]
I don't think this one is fixable without an overhaul with how the bot works.  Devs closed off the WebSocket this was using.

**Comment by Topinambur223606** [comment]
Updated version is released, please check latest release and close issue if it is fixed

**Comment by Topinambur223606** [comment]
Similar issue is closed so I think I can close this too
