### ISSUE TITLE
New placing way

### ISSUE THREAD

**Issue by Blazore71** [Topinambur223606/PixelPlanetTools#27]
Hi, 
I would like to know if it would be possible to improve the ways of placing a pixel ?

For example, when you set the bot to "top", he is placing pixels each line by each line, but randomly on that line. I would like a placing which for example place a pixel line by line but from left to right or right to left, like when you are placing pixels from your phone and you do lines.

Thanks for your response.

**Comment by Topinambur223606** [comment]
Yes, of course it's possible, I will add such options as soon as current issues will be handled.

**Comment by Topinambur223606** [comment]
Combined directional modes are included in the latest release.
Please check it and close the issue if implementation meets your expectations.

**Comment by Topinambur223606** [comment]
Hello @Blazore71,
May you please evaluate this update?

**Comment by Topinambur223606** [comment]
I will close this issue since it seems that it is no longer relevant.
Please feel free to open a new one if needed.
