### ISSUE TITLE
Infinite reconnect

### ISSUE THREAD

**Issue by ntomilin** [Topinambur223606/PixelPlanetTools#30]
Bot was working when internet provider disabled internet due to some their preventive work. Since then bot can't connect with websockets to pixeplanet. Before that I draw like 300k pixels, so it definitely works. After connection restored, bot still can't connect, tried to restart bot, tried to reboot PC and router. Captcha is solved. If I enter pixelplanet site I can sucessfully place pixels, no matter if its simple chrome or incognito, no troubles here. Also downloaded last version of .exe file for drawing, doesn't solve the problem. Not sure if it's some coincidance or it really has trouble connecting after interned disconnection because of provider.

Here you can see what error I see in the console: https://gist.github.com/ntomilin/5b7442e4448800200f16cb631d5a9aed
This is log file: https://gist.github.com/ntomilin/e121fb3c0e768acd30b68a9b7bb2a017

**Comment by JusSumBum** [comment]
has nothing to do with 

> Bot was working when internet provider disabled internet due to some their preventive work. Since then bot can't connect with websockets to pixeplanet. Before that I draw like 300k pixels, so it definitely works. After connection restored, bot still can't connect, tried to restart bot, tried to reboot PC and router. Captcha is solved. If I enter pixelplanet site I can sucessfully place pixels, no matter if its simple chrome or incognito, no troubles here. Also downloaded last version of .exe file for drawing, doesn't solve the problem. Not sure if it's some coincidance or it really has trouble connecting after interned disconnection because of provider.
> 
> Here you can see what error I see in the console: https://gist.github.com/ntomilin/5b7442e4448800200f16cb631d5a9aed
> This is log file: https://gist.github.com/ntomilin/e121fb3c0e768acd30b68a9b7bb2a017

Not about losing your internet connection. Mine stopped too. Same experience, but I didnt lose my internet connection.

**Comment by ntomilin** [comment]
Got it, closing issue than. Suppose something changed on site owners' side. Hope it will be fixed soon by itself.

**Comment by JusSumBum** [comment]
Yeah, not something to CLOSE. It is an issue. I reopened via new issue @ https://github.com/Topinambur223606/PixelPlanetTools/issues/31
