### ISSUE TITLE
Please make login to account

### ISSUE THREAD

**Issue by Cheryl3066009** [Topinambur223606/PixelPlanetTools#33]
Please make login to account, by post user name and password to https://pixelplanet.fun/api/auth/local

**Comment by Topinambur223606** [comment]
Please evaluate the feature added in the latest build and close the issue if it meets your expectations.

**Comment by Cheryl3066009** [comment]
bot always print that session expired but i created it two seconds ago

**Comment by Topinambur223606** [comment]
Somehow cookies do not work when saved "as is", but do when all properties except key and value are dropped.
That's completely my fault - I did not check the feature properly.
Since solution is already found, it will be fixed soon.

**Comment by Topinambur223606** [comment]
Please check the new release.
To migrate existing sessions instead of creating new, launch bot with verb `sessions` and it will offer you such possibility.

**Comment by Cheryl3066009** [comment]
thank you, l work fine
