### ISSUE TITLE
No se abre el archivo ejecutable y no se como abrir el zip

### ISSUE THREAD

**Issue by JoSiT02** [Topinambur223606/PixelPlanetTools#37]
al abrir el archivo ejecutable PixelPlanetBot.exe se abre el cmd y al instante se cierra
PD: soy nuevo en esto

**Comment by DarksliYT** [comment]
**cd directory of your pp bot
PixelPlanetBot.exe run -x * -y * -i *.png --notificationMode browser -d --placingOrder random
Pause**
Try this

**Comment by JoSiT02** [comment]
![descarga](https://user-images.githubusercontent.com/103158023/181596940-d03a5d9c-2482-4766-8a40-abbddb363187.png)

me sale error por que salen muchas coordenadas?
no se si esta todo bien
