### ISSUE TITLE
Closing the bot

### ISSUE THREAD

**Issue by Ratief** [Topinambur223606/PixelPlanetTools#39]
I haven't been able to figure out the correct way to exit the bot. CTRL-C doesn't seem to work. Nor does ESC or any other random CTRL+key that I've tried. So far the only way to exit that I've found is to kill the pid. Can you clarify the correct way to exit?

**Comment by Topinambur223606** [comment]
Ctrl+C was meant to be correct way, this is definitely a bug

**Comment by Topinambur223606** [comment]
Should be OK in 6.3.2
Please check the latest release and close the issue if it is fixed

**Comment by Topinambur223606** [comment]
If bug is still reproducible, please reopen the issue.
