### ISSUE TITLE
Maybe create bot for 3D canvas? 

### ISSUE THREAD

**Issue by msenya25** [Topinambur223606/PixelPlanetTools#4]

**Comment by Topinambur223606** [comment]
It means dealing with logging in, idk maybe later, but not in the nearest future

**Comment by Topinambur223606** [comment]
I don't have actual ideas how to set a template for 3d. The only thing that comes to my mind is a sequence of PNGs, layer by layer, but I'm not sure it is easy for users to create templates in that way.

**Comment by Mir0shi** [comment]
Why not to use some voxel editor? Then bot could read it and make it.

**Comment by Topinambur223606** [comment]
I found something called [sproxel](https://code.google.com/archive/p/sproxel/) and its exported CSV format looks very friendly for parsing. I think I can reference it as external editor for 3D templates.
Please view that application and evaluate its usability.

**Comment by Topinambur223606** [comment]
Such mode is implemented; please check latest version and readme
@msenya25, @moth-boi

**Comment by Topinambur223606** [comment]
Participants seem to be not responding and feature is implemented, so I'm closing the issue.
Feel free to open a new one if feature does not meet your expectations.
