### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Patrick1020** [Topinambur223606/PixelPlanetTools#40]
Hello , i have a problem , whenever i run the program it instantly closes .

**Comment by Topinambur223606** [comment]
Do you use command line arguments?
Check logs in `%appdata%\PixelPlanetTools\logs` folder if you do use arguments and it just dies.
Try launching from cmd to see its last output instead of getting window closed.

**Comment by Topinambur223606** [comment]
If problem is still relevant, reproducible and you are sure that program is started correctly, please reopen the issue and give more details.
