### ISSUE TITLE
The program chrashes/closes after i open it, any solutions for this??

### ISSUE THREAD

**Issue by ezezezezrs** [Topinambur223606/PixelPlanetTools#42]
It opens for a millisecond and the closes

**Comment by Topinambur223606** [comment]
Are you opening it with "double-click" or using CLI/script with arguments?
If you just "open" it as usual, it closes indeed - you need to pass arguments for it to work, please check readme.
If you know all this, arguments are valid and bot still struggles to launch - please describe in details what do you do, attaching logs will also help.

**Comment by ezezezezrs** [comment]
Im opening it by right clicking on the program, but it still closes. How can i pass those arguments?

**Comment by Topinambur223606** [comment]
Try searching on the internet how to use CMD or PowerShell, script files for them (.bat/.cmd or .ps1).
I'm closing the issue then.

**Comment by ezezezezrs** [comment]
It would be nice if you could help me on an other way, im still failing to launch the program, and im new to this stuff

**Comment by ezezezezrs** [comment]
Or could you just tell me how i can disable cooldown
