### ISSUE TITLE
problem with pixelwatcher

### ISSUE THREAD

**Issue by msenya25** [Topinambur223606/PixelPlanetTools#6]
![fgutoyuij](https://user-images.githubusercontent.com/29750228/74583545-33535280-4ff2-11ea-8038-c816c9f995e7.png)
I use that command 
`PixelPlanetWatcher.exe 22768 -19655 32767 -9656 logFileName2.txt`

**Comment by Topinambur223606** [comment]
Initial downloading and saving chunks are launched in background, recording changes is started at the very beginning too. In your case, recorded area is very huge (1600 chunks), so downloading and saving chunks is not finished before first minute passes, and there's no file created to write recorded changes to.

**Comment by Topinambur223606** [comment]
Check out latest release, it is updated with fixed version. Thank you for the report.

**Comment by msenya25** [comment]
Ok, thanks so much.
