### ISSUE TITLE
Problem with RecordVisualizer

### ISSUE THREAD

**Issue by msenya25** [Topinambur223606/PixelPlanetTools#7]
![fhjfhk](https://user-images.githubusercontent.com/29750228/74665155-4ec48600-51c9-11ea-8120-d3f43cadd216.png)
I tried to convert a huge area into an image.

**Comment by Topinambur223606** [comment]
Can you please upload a record file somewhere, I'll try to debug visualizer with it.

**Comment by Topinambur223606** [comment]
@msenya25 can you provide a record file that caused this error please? I'll try to debug visualizer using it

**Comment by msenya25** [comment]
ok

[pixels_(5555;5555)-(15554;15554)_2020.03.07_09-49.zip](https://github.com/Topinambur223606/PixelPlanetTools/files/4301348/pixels_.5555.5555.-.15554.15554._2020.03.07_09-49.zip)

**Comment by Topinambur223606** [comment]
I have tested visualizer using this file but I didn't get any errors.
Does this record file cause errors or just one that you mentioned earlier?
Does any record file cause errors? (please test with any small area)
If so, can you please send archived `%appdata%\PixelPlanetTools` folder? (there is no sensitive info).

**Comment by msenya25** [comment]
oh it actually works, sorry my bad.
