### ISSUE TITLE
problem with bot

### ISSUE THREAD

**Issue by msenya25** [Topinambur223606/PixelPlanetTools#8]
![ghkfghk](https://user-images.githubusercontent.com/29750228/76402447-a95a9780-63ad-11ea-859e-0853671ab412.png)

**Comment by Topinambur223606** [comment]
I suppose that it is caused by initial old logs cleanup in new folder that doesn't exist.
Achieved same behaviour when removed folder in %appdata%.
Please check if it is fixed in new release.

**Comment by Topinambur223606** [comment]
Hello @msenya25,
Attempt to clean logs in folder that doesn't exist caused apps to crash.
Please close issue if it is fixed in the latest release
