### ISSUE TITLE
Problem with RecordVisualizer

### ISSUE THREAD

**Issue by msenya25** [Topinambur223606/PixelPlanetTools#9]
![03 15_10-30-47](https://user-images.githubusercontent.com/29750228/76695345-60a22780-66a8-11ea-9272-335885ec14c4.png)

**Comment by Topinambur223606** [comment]
Please specify command line arguments and attach logs.
Logs are located at `%appdata%/PixelPlanetTools/logs/PixelPlanetWatcher/`,

**Comment by Topinambur223606** [comment]
Hello @msenya25,
Issue was actually caused not by visualizer - watcher was saving map to file in incorrect way.
Please check the latest release and close the issue if it's fixed.

P.S. I appreciate your reports, but they are a little bit incomplete. Please attach corresponding logs to bug issues. You can determine log file that you need by app-specific log folder, by log file name which contains date and time of launch, by command line arguments that are specified in the first line of log file.

**Comment by msenya25** [comment]
Ok
